# coding: utf-8

# flake8: noqa
"""
    Sample OpenAPI Specification

    An OpenAPI specification example for Building API services: A Beginners Guide document.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.error_message import ErrorMessage
from openapi_client.models.user import User
