# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from codegen import example_pb2 as example__pb2


class ExampleServiceStub(object):
  """Service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/ExampleService/GetUser',
        request_serializer=example__pb2.GetUserRequest.SerializeToString,
        response_deserializer=example__pb2.User.FromString,
        )


class ExampleServiceServicer(object):
  """Service definition
  """

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExampleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=example__pb2.GetUserRequest.FromString,
          response_serializer=example__pb2.User.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ExampleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
