# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, photos=None, next_page_token=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param photos: The photos of this InlineResponse200.  # noqa: E501
        :type photos: List[Photo]
        :param next_page_token: The next_page_token of this InlineResponse200.  # noqa: E501
        :type next_page_token: str
        """
        self.openapi_types = {
            'photos': List[Photo],
            'next_page_token': str
        }

        self.attribute_map = {
            'photos': 'photos',
            'next_page_token': 'next_page_token'
        }

        self._photos = photos
        self._next_page_token = next_page_token

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def photos(self):
        """Gets the photos of this InlineResponse200.


        :return: The photos of this InlineResponse200.
        :rtype: List[Photo]
        """
        return self._photos

    @photos.setter
    def photos(self, photos):
        """Sets the photos of this InlineResponse200.


        :param photos: The photos of this InlineResponse200.
        :type photos: List[Photo]
        """

        self._photos = photos

    @property
    def next_page_token(self):
        """Gets the next_page_token of this InlineResponse200.


        :return: The next_page_token of this InlineResponse200.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this InlineResponse200.


        :param next_page_token: The next_page_token of this InlineResponse200.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token
